import enum


class RoutineType(str, enum.Enum):
    DIAS = "DIAS"
    SEMANAS = "SEMANAS"
    FUNCIONAL = "FUNCIONAL"
    MUSCULACION = "MUSCULACION"
    PERSONALIZADA = "PERSONALIZADA"


class Role(str, enum.Enum):
    ADMINISTRADOR = "ADMINISTRADOR"
    ADMINISTRATIVO = "ADMINISTRATIVO"
    PROFESOR = "PROFESOR"
    ALUMNO = "ALUMNO"
    ADMIN = "ADMIN"
    RECEPCION = "RECEPCION"


class MembershipKind(str, enum.Enum):
    FUNCIONAL = "FUNCIONAL"
    MUSCULACION = "MUSCULACION"
    COMBINACION = "COMBINACION"
    CLASE_SUELTA = "CLASE_SUELTA"
    MENSUAL = "MENSUAL"
    QUINCENAL = "QUINCENAL"
    CLASES = "CLASES"
    OTRO = "OTRO"


class PaymentMethod(str, enum.Enum):
    LISTA = "LISTA"
    EFECTIVO = "EFECTIVO"
    TRANSFERENCIA = "TRANSFERENCIA"
    TARJETA = "TARJETA"
    OTRO = "OTRO"


class ServiceKind(str, enum.Enum):
    FUNCIONAL = "FUNCIONAL"
    MUSCULACION = "MUSCULACION"
    AMBOS = "AMBOS"
    OTRO = "OTRO"


class CashEntryType(str, enum.Enum):
    INGRESO = "INGRESO"
    EGRESO = "EGRESO"


class CashPaymentStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    ACREDITADO = "ACREDITADO"
    ANULADO = "ANULADO"
    PAGADO = "PAGADO"
    CANCELADO = "CANCELADO"


class CashSessionStatus(str, enum.Enum):
    ABIERTA = "ABIERTA"
    CERRADA = "CERRADA"


class CashExpenseCategory(str, enum.Enum):
    MEMBRESIA = "MEMBRESIA"
    INSUMOS = "INSUMOS"
    LIMPIEZA = "LIMPIEZA"
    MANTENIMIENTO = "MANTENIMIENTO"
    SERVICIOS = "SERVICIOS"
    SUELDOS = "SUELDOS"
    VARIOS = "VARIOS"


class CommercialStage(str, enum.Enum):
    NUEVO = "NUEVO"
    INTERESADO = "INTERESADO"
    CALIFICADO = "CALIFICADO"
    NEGOCIANDO = "NEGOCIANDO"
    DERIVADO = "DERIVADO"
    REACTIVADO = "REACTIVADO"
    CERRADO = "CERRADO"
    PERDIDO = "PERDIDO"
    CONTACTADO = "CONTACTADO"
    PRESENTACION = "PRESENTACION"
    NEGOCIACION = "NEGOCIACION"
    CIERRE_GANADO = "CIERRE_GANADO"
    CIERRE_PERDIDO = "CIERRE_PERDIDO"
    SEGUIMIENTO = "SEGUIMIENTO"


class FollowupKind(str, enum.Enum):
    MOROSIDAD = "MOROSIDAD"
    INACTIVIDAD = "INACTIVIDAD"
    GENERAL = "GENERAL"
    COBRO = "COBRO"
    ASISTENCIA = "ASISTENCIA"
    TECNICO = "TECNICO"
    COMERCIAL = "COMERCIAL"


class FollowupStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    CONTACTADO = "CONTACTADO"
    RESPONDIO = "RESPONDIO"
    REACTIVADO = "REACTIVADO"
    DESCARTADO = "DESCARTADO"
    EN_PROCESO = "EN_PROCESO"
    COMPLETADO = "COMPLETADO"
    CANCELADO = "CANCELADO"


class FollowupPriority(str, enum.Enum):
    BAJA = "BAJA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"
    CRITICA = "CRITICA"
    URGENTE = "URGENTE"


class FollowupChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    LLAMADA = "LLAMADA"
    PRESENCIAL = "PRESENCIAL"
    OTRO = "OTRO"
    TELEFONO = "TELEFONO"


class MessageTemplateChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    GENERAL = "GENERAL"
    SMS = "SMS"


class FollowupActionType(str, enum.Enum):
    MENSAJE_ENVIADO = "MENSAJE_ENVIADO"
    LLAMADA = "LLAMADA"
    EMAIL_ENVIADO = "EMAIL_ENVIADO"
    WHATSAPP_ENVIADO = "WHATSAPP_ENVIADO"
    RECORDATORIO = "RECORDATORIO"
    CAMBIO_ESTADO = "CAMBIO_ESTADO"
    NOTA = "NOTA"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    TAREA = "TAREA"
    OTRO = "OTRO"


class ProspectStatus(str, enum.Enum):
    NUEVO = "NUEVO"
    CALIFICANDO = "CALIFICANDO"
    INTERESADO = "INTERESADO"
    DERIVADO = "DERIVADO"
    CERRADO = "CERRADO"
    DESCARTADO = "DESCARTADO"
    CONTACTADO = "CONTACTADO"
    INSCRIPTO = "INSCRIPTO"


class ConversationType(str, enum.Enum):
    REACTIVACION = "REACTIVACION"
    NUEVO_PROSPECTO = "NUEVO_PROSPECTO"
    SOPORTE = "SOPORTE"
    GENERAL = "GENERAL"
    PROSPECTO = "PROSPECTO"
    COMERCIAL = "COMERCIAL"


class ConversationStatus(str, enum.Enum):
    ABIERTA = "ABIERTA"
    EN_AUTOMATICO = "EN_AUTOMATICO"
    DERIVADA_A_HUMANO = "DERIVADA_A_HUMANO"
    CERRADA = "CERRADA"
    NUEVA = "NUEVA"
    BOT = "BOT"
    HUMANO = "HUMANO"


class SenderType(str, enum.Enum):
    BOT = "BOT"
    HUMANO = "HUMANO"
    ALUMNO = "ALUMNO"
    PROSPECTO = "PROSPECTO"
    SISTEMA = "SISTEMA"
    USER = "USER"
    CONTACT = "CONTACT"
    SYSTEM = "SYSTEM"


class ClassStatus(str, enum.Enum):
    ACTIVA = "ACTIVA"
    INACTIVA = "INACTIVA"
    CANCELADA = "CANCELADA"


class Weekday(str, enum.Enum):
    LUNES = "LUNES"
    MARTES = "MARTES"
    MIERCOLES = "MIERCOLES"
    JUEVES = "JUEVES"
    VIERNES = "VIERNES"
    SABADO = "SABADO"
    DOMINGO = "DOMINGO"


class EnrollmentStatus(str, enum.Enum):
    ACTIVA = "ACTIVA"
    CANCELADA = "CANCELADA"
    ACTIVO = "ACTIVO"
    INACTIVO = "INACTIVO"
    LISTA_ESPERA = "LISTA_ESPERA"


class TemplateFollowupKind(str, enum.Enum):
    GENERAL = "GENERAL"
    RECORDATORIO_PAGO = "RECORDATORIO_PAGO"
    BIENVENIDA = "BIENVENIDA"
    REACTIVACION = "REACTIVACION"
    PROSPECTO = "PROSPECTO"


class ConversationChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    INSTAGRAM = "INSTAGRAM"
    FACEBOOK = "FACEBOOK"
    WEB = "WEB"
